# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kalk.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 666)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vyvod = QtWidgets.QLCDNumber(self.centralwidget)
        self.vyvod.setGeometry(QtCore.QRect(20, 20, 771, 61))
        self.vyvod.setDigitCount(40)
        self.vyvod.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.vyvod.setProperty("value", 0.0)
        self.vyvod.setObjectName("vyvod")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 210, 461, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.vosem = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vosem.sizePolicy().hasHeightForWidth())
        self.vosem.setSizePolicy(sizePolicy)
        self.vosem.setObjectName("vosem")
        self.gridLayout.addWidget(self.vosem, 0, 1, 1, 1)
        self.six = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.six.sizePolicy().hasHeightForWidth())
        self.six.setSizePolicy(sizePolicy)
        self.six.setObjectName("six")
        self.gridLayout.addWidget(self.six, 1, 2, 1, 1)
        self.seven = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seven.sizePolicy().hasHeightForWidth())
        self.seven.setSizePolicy(sizePolicy)
        self.seven.setObjectName("seven")
        self.gridLayout.addWidget(self.seven, 0, 0, 1, 1)
        self.five = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.five.sizePolicy().hasHeightForWidth())
        self.five.setSizePolicy(sizePolicy)
        self.five.setObjectName("five")
        self.gridLayout.addWidget(self.five, 1, 1, 1, 1)
        self.three = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.three.sizePolicy().hasHeightForWidth())
        self.three.setSizePolicy(sizePolicy)
        self.three.setObjectName("three")
        self.gridLayout.addWidget(self.three, 2, 2, 1, 1)
        self.two = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two.sizePolicy().hasHeightForWidth())
        self.two.setSizePolicy(sizePolicy)
        self.two.setObjectName("two")
        self.gridLayout.addWidget(self.two, 2, 1, 1, 1)
        self.one = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one.sizePolicy().hasHeightForWidth())
        self.one.setSizePolicy(sizePolicy)
        self.one.setObjectName("one")
        self.gridLayout.addWidget(self.one, 2, 0, 1, 1)
        self.nine = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nine.sizePolicy().hasHeightForWidth())
        self.nine.setSizePolicy(sizePolicy)
        self.nine.setObjectName("nine")
        self.gridLayout.addWidget(self.nine, 0, 2, 1, 1)
        self.four = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.four.sizePolicy().hasHeightForWidth())
        self.four.setSizePolicy(sizePolicy)
        self.four.setObjectName("four")
        self.gridLayout.addWidget(self.four, 1, 0, 1, 1)
        self.zero = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zero.sizePolicy().hasHeightForWidth())
        self.zero.setSizePolicy(sizePolicy)
        self.zero.setObjectName("zero")
        self.gridLayout.addWidget(self.zero, 3, 1, 1, 1)
        self.C = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
        self.C.setSizePolicy(sizePolicy)
        self.C.setObjectName("C")
        self.gridLayout.addWidget(self.C, 3, 0, 1, 1)
        self.point = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.point.sizePolicy().hasHeightForWidth())
        self.point.setSizePolicy(sizePolicy)
        self.point.setObjectName("point")
        self.gridLayout.addWidget(self.point, 3, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 90, 461, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(38, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dec = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.dec.setChecked(True)
        self.dec.setObjectName("dec")
        self.horizontalLayout.addWidget(self.dec)
        self.hex = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.hex.setObjectName("hex")
        self.horizontalLayout.addWidget(self.hex)
        self.oct = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.oct.setObjectName("oct")
        self.horizontalLayout.addWidget(self.oct)
        self.bin = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.bin.setObjectName("bin")
        self.horizontalLayout.addWidget(self.bin)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 461, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fact = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fact.sizePolicy().hasHeightForWidth())
        self.fact.setSizePolicy(sizePolicy)
        self.fact.setObjectName("fact")
        self.horizontalLayout_2.addWidget(self.fact)
        self.tgx = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tgx.sizePolicy().hasHeightForWidth())
        self.tgx.setSizePolicy(sizePolicy)
        self.tgx.setObjectName("tgx")
        self.horizontalLayout_2.addWidget(self.tgx)
        self.backspace = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backspace.sizePolicy().hasHeightForWidth())
        self.backspace.setSizePolicy(sizePolicy)
        self.backspace.setObjectName("backspace")
        self.horizontalLayout_2.addWidget(self.backspace)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(490, 90, 301, 531))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delB.sizePolicy().hasHeightForWidth())
        self.delB.setSizePolicy(sizePolicy)
        self.delB.setObjectName("delB")
        self.gridLayout_2.addWidget(self.delB, 3, 1, 1, 1)
        self.decreaceB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.decreaceB.sizePolicy().hasHeightForWidth())
        self.decreaceB.setSizePolicy(sizePolicy)
        self.decreaceB.setObjectName("decreaceB")
        self.gridLayout_2.addWidget(self.decreaceB, 4, 0, 1, 1)
        self.sqrtx = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sqrtx.sizePolicy().hasHeightForWidth())
        self.sqrtx.setSizePolicy(sizePolicy)
        self.sqrtx.setObjectName("sqrtx")
        self.gridLayout_2.addWidget(self.sqrtx, 2, 1, 1, 1)
        self.sinB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sinB.sizePolicy().hasHeightForWidth())
        self.sinB.setSizePolicy(sizePolicy)
        self.sinB.setObjectName("sinB")
        self.gridLayout_2.addWidget(self.sinB, 1, 0, 1, 1)
        self.logyx = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logyx.sizePolicy().hasHeightForWidth())
        self.logyx.setSizePolicy(sizePolicy)
        self.logyx.setObjectName("logyx")
        self.gridLayout_2.addWidget(self.logyx, 2, 0, 1, 1)
        self.log2xB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log2xB.sizePolicy().hasHeightForWidth())
        self.log2xB.setSizePolicy(sizePolicy)
        self.log2xB.setObjectName("log2xB")
        self.gridLayout_2.addWidget(self.log2xB, 3, 0, 1, 1)
        self.xsqr2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xsqr2.sizePolicy().hasHeightForWidth())
        self.xsqr2.setSizePolicy(sizePolicy)
        self.xsqr2.setObjectName("xsqr2")
        self.gridLayout_2.addWidget(self.xsqr2, 0, 1, 1, 1)
        self.mulB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mulB.sizePolicy().hasHeightForWidth())
        self.mulB.setSizePolicy(sizePolicy)
        self.mulB.setObjectName("mulB")
        self.gridLayout_2.addWidget(self.mulB, 4, 1, 1, 1)
        self.xsqry = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xsqry.sizePolicy().hasHeightForWidth())
        self.xsqry.setSizePolicy(sizePolicy)
        self.xsqry.setObjectName("xsqry")
        self.gridLayout_2.addWidget(self.xsqry, 0, 0, 1, 1)
        self.cosB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cosB.sizePolicy().hasHeightForWidth())
        self.cosB.setSizePolicy(sizePolicy)
        self.cosB.setObjectName("cosB")
        self.gridLayout_2.addWidget(self.cosB, 1, 1, 1, 1)
        self.addB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addB.sizePolicy().hasHeightForWidth())
        self.addB.setSizePolicy(sizePolicy)
        self.addB.setObjectName("addB")
        self.gridLayout_2.addWidget(self.addB, 5, 0, 1, 1)
        self.ravnoB = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ravnoB.sizePolicy().hasHeightForWidth())
        self.ravnoB.setSizePolicy(sizePolicy)
        self.ravnoB.setObjectName("ravnoB")
        self.gridLayout_2.addWidget(self.ravnoB, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.vosem.setText(_translate("MainWindow", "8"))
        self.six.setText(_translate("MainWindow", "6"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.five.setText(_translate("MainWindow", "5"))
        self.three.setText(_translate("MainWindow", "3"))
        self.two.setText(_translate("MainWindow", "2"))
        self.one.setText(_translate("MainWindow", "1"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.four.setText(_translate("MainWindow", "4"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.C.setText(_translate("MainWindow", "C"))
        self.point.setText(_translate("MainWindow", "."))
        self.dec.setText(_translate("MainWindow", "dec"))
        self.hex.setText(_translate("MainWindow", "hex"))
        self.oct.setText(_translate("MainWindow", "oct"))
        self.bin.setText(_translate("MainWindow", "bin"))
        self.fact.setText(_translate("MainWindow", "x!"))
        self.tgx.setText(_translate("MainWindow", "tg x"))
        self.backspace.setText(_translate("MainWindow", "==>"))
        self.delB.setText(_translate("MainWindow", "/"))
        self.decreaceB.setText(_translate("MainWindow", "-"))
        self.sqrtx.setText(_translate("MainWindow", "sqrt(x)"))
        self.sinB.setText(_translate("MainWindow", "sin(x)"))
        self.logyx.setText(_translate("MainWindow", "log y(x)"))
        self.log2xB.setText(_translate("MainWindow", "log 2(x)"))
        self.xsqr2.setText(_translate("MainWindow", "x ^ 2"))
        self.mulB.setText(_translate("MainWindow", "*"))
        self.xsqry.setText(_translate("MainWindow", "x ^ y"))
        self.cosB.setText(_translate("MainWindow", "cos(x)"))
        self.addB.setText(_translate("MainWindow", "+"))
        self.ravnoB.setText(_translate("MainWindow", "="))
